In [1]:
pip install striprtf

In [2]:
from striprtf.striprtf import rtf_to_text 
import pandas as pd

# read the RTF file into a pandas DataFrame
rtf = pd.read_csv("algoparams_from_ui.json.rtf", sep='\t', header=None)

# convert the DataFrame to a string
rtf_str = rtf.to_string(index=False, header=False)

# use striprtf to convert the RTF to plain text
text = rtf_to_text(rtf_str)

# print the plain text
print(text)

In [8]:
df=pd.read_csv("iris.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

iris = load_iris()
X = iris.data[:, 0].reshape(-1, 1)  # select sepal_length as feature and reshape to 2D array
y = iris.data[:, 3]  # select petal_width as target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Define regression model and train on training data
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Make predictions on testing data and evaluate model
y_pred = regressor.predict(X_test)
y_pred


array([1.17063462, 1.32164175, 0.94412393, 2.30318806, 0.56660612,
       1.54815243, 0.56660612, 1.85016668, 1.92567025, 1.39714531,
       1.39714531, 1.623656  , 1.39714531, 1.69915956, 1.39714531,
       0.49110256, 1.32164175, 0.94412393, 0.41559899, 0.86862037,
       1.01962749, 1.01962749, 0.41559899, 0.11358474, 1.47264887,
       0.26459187, 0.64210968, 1.47264887, 0.56660612, 0.56660612])

In [5]:
from sklearn.datasets import load_iris
from sklearn.impute import SimpleImputer
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

iris = load_iris()  # Call the function to load the dataset

# Create a list of the numerical feature names
num_feature_names = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

# Impute missing values for the numerical features
imputer = SimpleImputer(missing_values=-1, strategy='mean')
for feature_name in num_feature_names:
    feature_values = iris.data[:, iris.feature_names.index(feature_name)].reshape(-1, 1)
    iris.data[:, iris.feature_names.index(feature_name)] = imputer.fit_transform(feature_values).ravel()

# Tokenize and hash the "species" text feature
vectorizer = CountVectorizer(token_pattern=r'\b\w+\b')
X_species = vectorizer.fit_transform(iris.target_names[iris.target])
hashed_feature_names = vectorizer.get_feature_names()

# Combine the numerical and text features into a single feature matrix
X_num = iris.data
X_all = np.hstack((X_num, X_species.toarray()))

# Print the final feature matrix
print("Final feature matrix:\n", X_all)


Final feature matrix:
 [[5.1 3.5 1.4 ... 1.  0.  0. ]
 [4.9 3.  1.4 ... 1.  0.  0. ]
 [4.7 3.2 1.3 ... 1.  0.  0. ]
 ...
 [6.5 3.  5.2 ... 0.  0.  1. ]
 [6.2 3.4 5.4 ... 0.  0.  1. ]
 [5.9 3.  5.1 ... 0.  0.  1. ]]


C:\Users\manin\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [21]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

# Create a Pandas DataFrame to store the dataset
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                  columns= iris['feature_names'] + ['target'])

# Compute the correlation coefficients between each feature and the target variable
correlations = df.corr()['target'][:-1]

# Select the top n features based on their correlation coefficients
n = 2
top_n_features = correlations.abs().nlargest(n).index.tolist()

# Extract the selected features from the dataset
X_reduced = df[top_n_features].values
X_reduced


array([[0.2, 1.4],
       [0.2, 1.4],
       [0.2, 1.3],
       [0.2, 1.5],
       [0.2, 1.4],
       [0.4, 1.7],
       [0.3, 1.4],
       [0.2, 1.5],
       [0.2, 1.4],
       [0.1, 1.5],
       [0.2, 1.5],
       [0.2, 1.6],
       [0.1, 1.4],
       [0.1, 1.1],
       [0.2, 1.2],
       [0.4, 1.5],
       [0.4, 1.3],
       [0.3, 1.4],
       [0.3, 1.7],
       [0.3, 1.5],
       [0.2, 1.7],
       [0.4, 1.5],
       [0.2, 1. ],
       [0.5, 1.7],
       [0.2, 1.9],
       [0.2, 1.6],
       [0.4, 1.6],
       [0.2, 1.5],
       [0.2, 1.4],
       [0.2, 1.6],
       [0.2, 1.6],
       [0.4, 1.5],
       [0.1, 1.5],
       [0.2, 1.4],
       [0.2, 1.5],
       [0.2, 1.2],
       [0.2, 1.3],
       [0.1, 1.4],
       [0.2, 1.3],
       [0.2, 1.5],
       [0.3, 1.3],
       [0.3, 1.3],
       [0.2, 1.3],
       [0.6, 1.6],
       [0.4, 1.9],
       [0.3, 1.4],
       [0.2, 1.6],
       [0.2, 1.4],
       [0.2, 1.5],
       [0.2, 1.4],
       [1.4, 4.7],
       [1.5, 4.5],
       [1.5,

In [23]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import ExtraTreesRegressor

iris = load_iris()

# Create a Pandas DataFrame to store the dataset
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                  columns= iris['feature_names'] + ['target'])

# Split the dataset into input features and target variable
X = df.drop('target', axis=1)
y = df['target']

# Train an ExtraTreesRegressor model to compute feature importance
model = ExtraTreesRegressor(n_estimators=100, random_state=42)
model.fit(X, y)

# Select the top n features based on their feature importance scores
n = 2
top_n_features = np.argsort(model.feature_importances_)[::-1][:n]

# Extract the selected features from the dataset
X_reduced = X.iloc[:, top_n_features].values
X_reduced


array([[0.2, 1.4],
       [0.2, 1.4],
       [0.2, 1.3],
       [0.2, 1.5],
       [0.2, 1.4],
       [0.4, 1.7],
       [0.3, 1.4],
       [0.2, 1.5],
       [0.2, 1.4],
       [0.1, 1.5],
       [0.2, 1.5],
       [0.2, 1.6],
       [0.1, 1.4],
       [0.1, 1.1],
       [0.2, 1.2],
       [0.4, 1.5],
       [0.4, 1.3],
       [0.3, 1.4],
       [0.3, 1.7],
       [0.3, 1.5],
       [0.2, 1.7],
       [0.4, 1.5],
       [0.2, 1. ],
       [0.5, 1.7],
       [0.2, 1.9],
       [0.2, 1.6],
       [0.4, 1.6],
       [0.2, 1.5],
       [0.2, 1.4],
       [0.2, 1.6],
       [0.2, 1.6],
       [0.4, 1.5],
       [0.1, 1.5],
       [0.2, 1.4],
       [0.2, 1.5],
       [0.2, 1.2],
       [0.2, 1.3],
       [0.1, 1.4],
       [0.2, 1.3],
       [0.2, 1.5],
       [0.3, 1.3],
       [0.3, 1.3],
       [0.2, 1.3],
       [0.6, 1.6],
       [0.4, 1.9],
       [0.3, 1.4],
       [0.2, 1.6],
       [0.2, 1.4],
       [0.2, 1.5],
       [0.2, 1.4],
       [1.4, 4.7],
       [1.5, 4.5],
       [1.5,

In [18]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.ensemble import ExtraTreesRegressor

iris = load_iris()

# Create a Pandas DataFrame to store the dataset
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                  columns= iris['feature_names'] + ['target'])

# Split the dataset into input features and target variable
X = df.drop('target', axis=1)
y = df['target']

# Train an ExtraTreesRegressor model to compute feature importance
model = ExtraTreesRegressor(n_estimators=100, random_state=42)
model.fit(X, y)

# Select the top n features based on their feature importance scores
n = 2
top_n_features = np.argsort(model.feature_importances_)[::-1][:n]

# Extract the selected features from the dataset
X_reduced = X.iloc[:, top_n_features].values


In [19]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA

iris = load_iris()

# Create a Pandas DataFrame to store the dataset
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                  columns= iris['feature_names'] + ['target'])

# Split the dataset into input features and target variable
X = df.drop('target', axis=1)
y = df['target']

# Instantiate a PCA object and fit it to the input features
n_components = 2
pca = PCA(n_components=n_components)
X_reduced = pca.fit_transform(X)

# Print the explained variance ratios of each principal component
print("Explained variance ratios:", pca.explained_variance_ratio_)


Explained variance ratios: [0.92461872 0.05306648]
